services:
  server:
    build: ./server
    ports:
      - "8443:8443"
    environment:
      - PORT=8443
      - DATABASE_URL=postgresql://user:password@db:5432/challengefit
      - NODE_ENV=production
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=challengefit
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5555:5432"

volumes:
  postgres_data:
