export const Config = {
  STEP_THRESHOLD_PER_MISSION: 2000,
  DAILY_STEP_GOAL: 6000,
  STATIONARY_THRESHOLD_MINUTES: 40,
  SNOOZE_MINUTES: 15,
  MAX_DAILY_MISSIONS: 3,
  REFRESH_COOLDOWN_HOURS: 12,
  CHECK_MISSIONS_INTERVAL: 60000,
  MOCK_STATIONARY_ADDITIONAL_MINUTES: 5,
};
